### ISSUE TITLE
ValueError: All layers added to a Sequential model should have unique names.

### ISSUE THREAD

**Issue by JavierOrjuela** [deepsphere/deepsphere-cosmo-tf2#2]
Hello, 
I am getting an error when I am running either 'pytest tests' or the quick_start notebook. This error is: "ValueError: All layers added to a Sequential model should have unique names. Name "" is already the name of a layer in this model. Update the `name` argument to pass a unique name."; 
which appears during the creation of the model:
model = HealpyGCNN(nside=nside, indices=indices, layers=layers, n_neighbors=20).   

I am running deepsphere-cosmotf2 in tf.2.7 and python3.8.10.  Anyone has ideas to solve the problem? 
Thank you very much.

**Comment by jafluri** [comment]
Hello,

Thanks a lot for your interest in DeepSphere for TF 2.x.

TF does not allow multiple layers to have the same name anymore and the default behaviour for the custom layers in DeepSphere was to set all names to empty strings. This should be fixed by ec7700ce6a10d4742deb9ae3d67a482ed8db4e15.

Let me know if you still have issues.

**Comment by JavierOrjuela** [comment]
It works now! Thanks
